services:
  spa:
    build: backend
    container_name: backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend/spaproject:/app

  frontend:
    build:
      context: ./frontend
      args:
        - SECRET_KEY=${SECRET_KEY}
        - DEBUG=${DEBUG}
        - CERTS=${CERTS}
        - COUNTRY=${COUNTRY}
        - STATE=${STATE}
        - LOCALITY=${LOCALITY}
        - ORGANIZATION=${ORGANIZATION}
        - ORGANIZATION_UNIT=${ORGANIZATION_UNIT}
        - COMMON_NAME=${DOMAIN_NAME}
        - EMAIL=${EMAIL}
        - DOMAIN_NAME=${DOMAIN_NAME}
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/static_vol:/var/www/html
      - ${CERTS}:/etc/nginx/ssl:ro
